{% set name = "openff-bespokefit" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-bespokefit/archive/refs/tags/{{ version }}.tar.gz
  sha256: edd5a707c22ccfe9b3a238282e501ae169f052a067a33fa2b0cc0f2f6129e5a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - pydantic =1
    - pyyaml
    - tqdm
    - rich
    - click >=8.0.0
    - click-option-group
    - rdkit
    - openff-utilities
    - openff-toolkit-base >=0.11,<0.14
    - openff-interchange
    - openff-units =0.2
    - openff-forcefields
    - openff-qcsubmit <0.50
    - forcebalance =1.9.6
    - openff-fragmenter-base >=0.1.2
    - openmm >=7.6.0
    - qcportal =0.15
    - qcengine >=0.25.0
    - qcelemental >=0.25.1
    - chemper
    - geometric =1
    - torsiondrive
    - uvicorn
    - fastapi
    - celery >=5.0.0
    - httpx
    - redis-server
    - redis-py
  run_constrained:
    - starlette =0.20
    - h5py >=3.6

test:
  imports:
    - openff.bespokefit
  commands:
    - openff-bespoke --help

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated tools for the generation of bespoke SMIRNOFF format parameters for individual molecules.
  dev_url: https://github.com/openforcefield/openff-bespokefit

extra:
  recipe-maintainers:
    - j-wags
    - mattwthompson
    - jthorton
    - SimonBoothroyd
    - Yoshanuikabundi 
